### ISSUE TITLE
Build on x86 fails since 05b9b13cf857c9388e6a211203b2af2386553ee0 with rust 1.60.0

### ISSUE THREAD

**Issue by sqozz** [librespot-org/librespot#1033]
I tried to update librespot onto the newest commits from the dev-branch but realized that cargo fails to build with the following error:

```
$ cargo build --release
   Compiling enum-iterator v1.1.3
   Compiling hyper v0.14.20
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.1.3/src/lib.rs:82:26
   |
82 | pub const fn cardinality<T: Sequence>() -> usize {
   |                          ^
   |
   = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `enum-iterator` due to previous error
warning: build failed, waiting for other jobs to finish...
^C  Building [======================>  ] 328/343: hyper
```

I bisected and found `05b9b13cf857c9388e6a211203b2af2386553ee0` as first "bad" commit where it fails. The one before builds just fine on the same host with the same rust/cargo/etc. versions:

rust 1.60.0 (d1fd9fe 2022-03-01)

**Comment by sqozz** [comment]
I realized that there was a rust update for my gentoo system to 1.62.1 (a748cf5a3 2022-06-08). With the newest version everything builds fine again. Is it worth a note somewhere in the docs that for dev/new-api at least rust 1.62.1 is required?

**Comment by roderickvd** [comment]
It is already in the compiling docs. Though I believe you can now also specify it in the Cargo manifest. Feel free to put in a PR if you want to.

**Comment by sqozz** [comment]
duh, I've missed that, sorry. PR created in https://github.com/librespot-org/librespot/pull/1034 - thanks!
