### PR TITLE
Fix: Add missing feature for `with-avahi` feature

### LINKED ISSUE #1598: Unable to compile since recent `features` change
### Description
Compilation error on latest `dev`, https://github.com/librespot-org/librespot/commit/eb7c65e77b60da6544e2f4c1bbf3ba06705ef1b7. This is broken since https://github.com/librespot-org/librespot/commit/6f6cd04874b09736bd17879363d1c0a387bc9440 (aka. https://github.com/librespot-org/librespot/pull/1543), the commit prior (https://github.com/librespot-org/librespot/commit/df5f957bdd9a29801dd16f08cdc9abc580912da7) to this change is fine.

### Version
https://github.com/librespot-org/librespot/commit/eb7c65e77b60da6544e2f4c1bbf3ba06705ef1b7

### How to reproduce

Run:

```bash
cargo build  --no-default-features --features "rodio-backend with-avahi native-tls" --release
```

Fails with:

```
   Compiling librespot-discovery v0.7.1 (/home/meril/librespot/discovery)
error[E0433]: failed to resolve: could not find `poll` in `futures_util`
   --> discovery/src/lib.rs:201:60
    |
201 |             while let Poll::Ready(Some(_)) = futures_util::poll!(stream.next()) {
    |                                                            ^^^^ could not find `poll` in `futures_util`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `librespot-discovery` (lib) due to 1 previous error
```

### Host:
- OS: Arch Linux
- Platform: x64
- `rustup show`

```
installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (active, default)
```

- `rustc --version`

```
rustc 1.90.0 (1159e78c4 2025-09-14)
```

### PR DESCRIPTION
**Pull request by photovoltex**
Fixes #1598

### CODE REVIEW

**Comment by roderickvd** [comment]
Thanks for the quick fix. Would it be useful to prevent regression in the CI?

**Comment by photovoltex** [comment]
Would probably help here yeah. But I will do that tomorrow then.

**Comment by kimtore** [comment]
This issue affects the build of Raspotify.
Would be nice to get this merged before the next release. :)

**Comment by photovoltex** [comment]
Good reminder, will try to see it done with the next release^^

**Comment by roderickvd** [comment]
> Good reminder, will try to see it done with the next release^^

I'm pushing the check to your repo hoping to merge this one also.
